spring:
  datasource:
    url: jdbc:postgresql://account-db:5433/account_db
#    url: jdbc:postgresql://localhost:5433/account_db
    username: account_user
    password: 123456789
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/