spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/accounts/**
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/transactions/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: read-only
eureka:
  client:
    serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

