spring:
  application:
    name: monolith-app
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: account_user
    password: 123456789
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: k8YsLp6dyOudDsKKbAk+WJ4QQTlJufbKM42TLd/Vnks=